import type { Metadata } from "next";
import { SidebarProvider } from "@/components/ui/sidebar";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <SidebarProvider>
        <html lang="en">
          <body className="flex w-screen h-screen bg-[#F0F0FA]">
            <main className="flex border justify-center items-center w-full h-full">
              {children}
            </main>
          </body>
        </html>
      </SidebarProvider>
    </ClerkProvider>
  );
}
