import type { Metadata } from "next";
import { Navbar } from "../components/navbar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SidebarProvider>
        <body className="flex w-screen h-screen bg-white">
          <Navbar />
          <main className="flex border justify-center items-center w-full h-full">
            {children}
          </main>
        </body>
      </SidebarProvider>
    </html>
  );
}
