import type { Metadata } from "next";
import { SidebarProvider } from "@/components/ui/sidebar";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <html lang="en">
        <body className="flex w-screen h-screen bg-grey-main">
          <main className="flex w-full h-full">{children}</main>
        </body>
      </html>
    </SidebarProvider>
  );
}
